### PR TITLE
Exec tachikoma update 20150212021427

### PR DESCRIPTION
**Pull request by tachikomapocket**
:hamster::hamster::hamster: <br /> <br /> Strategy bundler
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5971460987633221050">Bundle Update as a Service - Tachikoma.io</a>

### CODE REVIEW

**Comment by masutaka** [comment]
* [addressable](https://github.com/sporkmonger/addressable): 2.3.6 => 2.3.7
* eventmachine: https://github.com/eventmachine/eventmachine/compare/v1.0.6...v1.0.7
* [puma](http://puma.io): 2.11.0 => 2.11.1

Powered by [compare_linker](https://github.com/kyanny/compare_linker)

**Comment by masutaka** [comment]
手動でcompare_linker使ってみた。
http://masutaka.net/chalow/2015-02-08-1.html

**Comment by masutaka** [comment]
ビルドできているので問題ないだろう

**Comment by hoshinotsuyoshi** [comment]
:+1:

**Pull request merged**
