### PR TITLE
Bundle Update on 2015-10-28

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [celluloid](https://github.com/celluloid/celluloid), [0.16.1...0.16.0](https://github.com/celluloid/celluloid/compare/v0.16.1...v0.16.0) ([CHANGELOG](https://github.com/celluloid/celluloid/blob/master/CHANGES.md))
- Updated: [minitest](https://github.com/seattlerb/minitest), 5.8.1...5.8.2 ([CHANGELOG](https://github.com/seattlerb/minitest/blob/master/History.rdoc))

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Dependency Updates
2 Pull Requests sent and 1 minute, and 14 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by tmd45** [comment]
> Updated: celluloid, 0.16.1...0.16.0 (CHANGELOG)

んえ、下がった？？？

**Comment by tmd45** [comment]
0.16.1 yanked! https://rubygems.org/gems/celluloid/versions

**Comment by tmd45** [comment]
まぁ問題ないんじゃないかな

**Comment by hoshinotsuyoshi** [comment]
LGTM〜

**Comment by masutaka** [comment]
あざっす！

**Pull request merged**
